.babelrc.json
.storybook/main.ts
.storybook/preview.ts
package.json
src/FunEatProvider.tsx
src/index.ts
src/styles/GlobalStyle.ts
src/styles/theme.ts
webpack.config.js
yarn.lock

- close #1
- `FunEatProvider` 추가
- GlobalStyle 추가
- theme.ts 추가
- x
- x

feat: 글로벌 스타일 적용

---

.storybook/main.ts
.storybook/preview.tsx

- close #11
- 스토리북에 웹팩 설정
- 스토리북에 GlobalStyle 적용
x
x

chore: 스토리북에 웹팩 설정 및 GlobalStyle 적용

---

.babelrc.json
package.json
src/styles/styled.d.ts
src/styles/theme.ts
yarn.lock

- close #21 
- babel-styled-components plugin 설치
- styled.d.ts 파일 추가
x
x

chore: css props 추가를 위한 babel plugin 및 타입 추가

---

src/Divider/Divider.stories.tsx
src/Divider/Divider.tsx
src/Divider/index.ts

- close #8 
- divider의 디자인 시스템을 구현하였습니다.
x
x

feat: divider 디자인 시스템 구현

---

src/Badge/Badge.stories.tsx
src/Badge/Badge.tsx
src/Badge/index.ts
src/types.ts

- close #5
- Badge 컴포넌트 구현
- Size type 선언 (xs, sm, md, lg, xl)
x
x

feat: Badge 컴포넌트 추가

---

src/Badge/Badge.tsx
src/BottomSheet/BottomSheet.tsx
src/Button/Button.tsx
src/Divider/Divider.stories.tsx
src/Spacing/Spacing.stories.tsx
src/Spacing/Spacing.tsx
src/Text/Text.tsx
src/index.ts
src/styles/styled.d.ts
src/type.ts
src/types.ts

- close #23
- 컴포넌트 컨벤션 맞추기
- index.ts 파일 추가
x
- 문서 작성, 버전 업, 배포, 레쓰고

refactor: 컨벤션 맞추기

---

src/Checkbox/Checkbox.stories.tsx
src/Checkbox/Checkbox.tsx
src/Checkbox/index.ts
src/index.ts

- close #36 
- Checkbox 컴포넌트 추가
- 체크 상태에서 배경색과 체크색 추천 받습니다. 우선 배경색 primary 컬러로 했습니다.
x

feat: Checkbox 컴포넌트 추가

---

src/Textarea/Textarea.stories.tsx
src/Textarea/Textarea.tsx
src/Textarea/index.ts
src/index.ts
src/styles/theme.ts

- close #3 
- Textarea 컴포넌트
- 에러 상황에 대한 디자인은 따로 처리 안했는데 우선 기본틀만 만들었습니다.
- 리뷰 작성 페이지에 Input이 없어 우선 Textarea만 올립니다.

feat: Textarea 컴포넌트 추가

---

src/Badge/Badge.tsx

- close #41 
- button 내부에 div태그가 들어가는 것이 시맨틱 하지 않아 수정했습니다.
x
x

feat: Badge 컴포넌트를 div에서 span태그로 변경

---

src/BottomSheet/BottomSheet.tsx
src/styles/animations.ts

- close #43
bottom sheet가 maxWidth를 받아 해당 maxWidth로 크기를 조절할 수 있도록 수정하였습니다.
이에 따라 animation 또한 bottom으로 바꾸었습니다.
x
x

refactor: bottom sheet maxWidth 받도록 수정

---

src/BottomSheet/BottomSheet.stories.tsx
src/BottomSheet/BottomSheet.tsx
src/BottomSheet/index.ts
src/BottomSheet/useBottomSheet.ts
src/index.ts

- close #45 
- useBottomSheet 훅을 디자인 시스템으로 이동시켰습니다.
- maxWidth를 수정하였습니다.
x
x

Bottom Sheet 수정

---

README.md
src/Button/Button.stories.tsx
src/Button/Button.tsx

- close #40 
- 버튼의 투명 버전을 추가하였습니다.
- 버튼의 기존 size를 없애고 props를 추가하였습니다.
투명 버전의 경우 width가 없이 쓰는 경우가 많은 거 같아서 fit-content로 설정했는데 어떤가요?
x

Button 컴포넌트 수정

---

src/BottomSheet/BottomSheet.tsx

- close #48 
- Bottom Sheet의 높이보다 큰 content가 들어와도 담을 수 있도록 max height를 설정하였습니다. 
- y축 스크롤을 생성하고, 안보이도록 설정하였습니다.
x
x

Bottom Sheet max height 설정과 y축 스크롤 생성

---

.github/release-drafter.yml
.github/workflows/release.yml

- close #50 
- 배포 및 릴리즈 노트 자동화
x
x

chore: 배포 및 릴리즈 노트 yml 작성

---

src/BottomSheet/BottomSheet.tsx

- close #59
- `height: fit-content` 속성 제거
x
x

fix: 사파리에서 바텀시트 안 열리는 오류 해결

---

README.md
src/Badge/Badge.tsx

- close #64 
- span으로 하니까 높이가 설정되지 않아 p태그도 사용할 수 있게 함
x
x

feat: Badge 컴포넌트에 p, span 태그 둘 다 사용할 수 있게끔 변경

---

src/Text/Text.tsx

- close #66 
Text에 css 속성이 적용되도록 수정해보았습니다.
만약에 성공하면 다른 부분도 css를 받을 수 있도록 할 예정이고,
실패하면 해당 로직은 삭제할 예정입니다.
- 특이 사항이 있으면 작성합니다.
빠른 적용을 위해 먼저 merge 해보겠습니다.

fix: text에 css 속성 적용되도록 수정

---

src/BottomSheet/BottomSheet.tsx

- close #71 
버그 수정이여서 직접 머지 시키겠습니다.
만약 또 이거 때문에 오류가 생긴다면 다시 지울게요 🥲

fix: dialog protal 위치 변경

---

src/BottomSheet/BottomSheet.stories.tsx
src/BottomSheet/BottomSheet.tsx
src/BottomSheet/useBottomSheet.ts

- close #73 
dialog를 div role dialog로 변경하였습니다.
x
x

refactor: dialog를 div role dialog로 변경

---

README.md
src/Skeleton/Skeleton.stories.tsx
src/Skeleton/Skeleton.tsx
src/Skeleton/index.ts
src/index.ts

- close #78
Skeleton을 옮겼습니다.
앞 파일에서 리드미 전격 수정으로 인해 충돌날 거 같아서 여기는 추가 안했어요.
앞 파일 머지되면 넣을게요
노션에는 추가해뒀습니다!
x

Skeleton 추가

---

src/Text/Text.stories.tsx
src/Text/Text.tsx
src/Text/text.module.css
src/styles/font.css

- close #91 
- Text 컴포넌트 css module 적용
- 인라인으로 css 지역 변수 설정해서 prop으로 받은 값을 활용하도록 했습니다.
- 추가 스타일이 필요하면 css 객체를 넣어서 사용하면 됩니다.
- p, span 혼합 사용에서 좀 애먹었지만.. 코파일럿과 때려맞추기로 함께 해결했슴다.
- line-height는 변수로 설정한게 없어 우선 삭제했습니다.
- 스토리북 확인해보세요 😊

feat: Text 컴포넌트 버전업
